version: '2'

networks:
  hypersub:

services:
  couchdb_nexnet:
    container_name: couchdb_nexnet
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=nexnet
      - COUCHDB_PASSWORD=nexnet
    ports:
      - "5984:5984"
    networks:
      - hypersub


  peer0.nexnet.hypersub.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_nexnet:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=nexnet
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=nexnet
    depends_on:
      - couchdb_nexnet


  couchdb_xorg:
    container_name: couchdb_xorg
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=xorg
      - COUCHDB_PASSWORD=xorg
    ports:
      # reach all dbs on same local port
      - "6984:5984"
    networks:
      - hypersub


  peer0.xorg.hypersub.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_xorg:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=xorg
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=xorg
    depends_on:
      - couchdb_xorg

  couchdb_auditor:
    container_name: couchdb_auditor
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=auditor
      - COUCHDB_PASSWORD=auditor
    ports:
      # reach all dbs on same local port
      - "7984:5984"
    networks:
      - hypersub


  peer0.auditor.hypersub.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_auditor:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=auditor
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=auditor
    depends_on:
      - couchdb_auditor


  couchdb_debtcollector:
    container_name: couchdb_debtcollector
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=debtcollector
      - COUCHDB_PASSWORD=debtcollector
    ports:
      # reach all dbs on same local port
      - "8984:5984"
    networks:
      - hypersub

  peer0.debtcollector.hypersub.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_debtcollector:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=debtcollector
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=debtcollector
    depends_on:
      - couchdb_auditor
