version: '3.7'

networks:
  poc-hypersub:
    name: poc-hypersub

services:
  poc-server:
    container_name: poc-server
    build:
      context: ../hypersub/server
      dockerfile: Dockerfile
    ports:
      - 3031:3031
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '../hypersub/server:/home/node/app'
      - '/home/node/app/node_modules'
    command: npm start
    stdin_open: true
    networks:
      - poc-hypersub



  poc-client:
    container_name: poc-client
    build:
      context: ../hypersub/poc-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '../hypersub/poc-app:/home/node/app'
      - '/home/node/app/node_modules'
    command: npm start
    stdin_open: true
    networks:
      - poc-hypersub


