################################################################################
#
#   ORGANIZATIONS
#
#   This section defines the organizational identities that can be referenced
#   in the configuration profiles.
#
################################################################################
Organizations:
  - &Nexnet
    Name: Nexnet
    SkipAsForeign: false
    ID: nexnetMSP
    MSPDir: ../organizations/peerOrganizations/nexnet.hypersub.com/msp
    Policies: &C1SignaturePolicies
      Readers:
        Type: Signature
        Rule: "OR('nexnetMSP.admin', 'nexnetMSP.peer', 'nexnetMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('nexnetMSP.admin', 'nexnetMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('nexnetMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('nexnetMSP.peer')"
    AnchorPeers:
      - Host: peer0.xorg.hypersub.com
        Port: 8051
      - Host: peer0.auditor.hypersub.com
        Port: 9051
      - Host: peer0.debtcollector.hypersub.com
        Port: 10051

  - &Xorg
    Name: Xorg
    SkipAsForeign: false
    ID: xorgMSP
    MSPDir: ../organizations/peerOrganizations/xorg.hypersub.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('xorgMSP.admin', 'xorgMSP.peer', 'xorgMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('xorgMSP.admin', 'xorgMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('xorgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('xorgMSP.peer')"
    AnchorPeers:
      - Host: peer0.nexnet.hypersub.com
        Port: 7051
      - Host: peer0.auditor.hypersub.com
        Port: 9051
      - Host: peer0.debtcollector.hypersub.com
        Port: 10051

  - &Auditor
    Name: Auditor
    SkipAsForeign: false
    ID: auditorMSP
    MSPDir: ../organizations/peerOrganizations/auditor.hypersub.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('auditorMSP.admin', 'auditorMSP.peer', 'auditorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('auditorMSP.admin', 'auditorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('auditorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('auditorMSP.peer')"
    AnchorPeers:
      - Host: peer0.nexnet.hypersub.com
        Port: 7051
      - Host: peer0.xorg.hypersub.com
        Port: 8051
      - Host: peer0.debtcollector.hypersub.com
        Port: 10051

  - &DebtCollector
    Name: DebtCollector
    SkipAsForeign: false
    ID: debtcollectorMSP
    MSPDir: ../organizations/peerOrganizations/debtcollector.hypersub.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('debtcollectorMSP.admin', 'debtcollectorMSP.peer', 'debtcollectorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('debtcollectorMSP.admin', 'debtcollectorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('debtcollectorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('debtcollectorMSP.peer')"
    AnchorPeers:
      - Host: peer0.nexnet.hypersub.com
        Port: 7051
      - Host: peer0.xorg.hypersub.com
        Port: 8051
      - Host: peer0.auditor.hypersub.com
        Port: 9051


  - &OrdererOrg
    Name: OrdererOrg
    ID: ordererMSP
    MSPDir: ../organizations/ordererOrganizations/hypersub.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ordererMSP.admin')"
    OrdererEndpoints:
      - "orderer.hypersub.com:7050"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults
  ACLs: &ACLsDefault
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers
    _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Readers
    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers
    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetConfigTree: /Channel/Application/Readers
    cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
    peer/Propose: /Channel/Application/Writers
    peer/ChaincodeToChaincode: /Channel/Application/Readers
    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers

  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ApplicationCapabilities

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaultSettings

  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
      - Host: orderer.hypersub.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/hypersub.com/orderers/orderer.hypersub.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/hypersub.com/orderers/orderer.hypersub.com/tls/server.crt
    Options:
      TickInterval: 500ms
      ElectionTick: 10
      HeartbeatTick: 1
      MaxInflightBlocks: 5
      SnapshotIntervalSize: 16 MB
  Addresses:
    - orderer.hypersub.com:7050

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaultSettings
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
  HypersubGenesis:
    <<: *ChannelDefaultSettings
    Orderer:
      <<: *OrdererDefaultSettings
      Organizations:
        - *OrdererOrg
        - *Xorg
        - *DebtCollector
        - *Auditor
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      ConsortiumOne:
        Organizations:
          - *Nexnet
          - *Xorg
          - *Auditor
      ConsortiumTwo:
        Organizations:
          - *Nexnet
          - *Xorg
          - *DebtCollector

  Channel1:
    <<: *ChannelDefaultSettings
    Consortium: ConsortiumOne
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Nexnet
        - *Xorg
        - *Auditor
      Capabilities:
        <<: *ApplicationCapabilities


  Channel2:
    <<: *ChannelDefaultSettings
    Consortium: ConsortiumTwo
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Nexnet
        - *Xorg
        - *DebtCollector
      Capabilities:
        <<: *ApplicationCapabilities

